name: Docker Image CI

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.1

            - name: Login to Container registry
              uses: docker/login-action@v3.0.0
              with:
                  registry: geoguide.azurecr.io
                  username: ${{ secrets.DOCKER_REGISTRY_UNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PWORD }}

            - name: Build the Docker image
              run: docker build -t geoguide.azurecr.io/server:latest .

            - name: Push the Docker image
              run: docker push geoguide.azurecr.io/server:latest

            - name: Deploy on Azure VM
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      bash ~/GeoGuide/update.sh
