name: Jest Tests

on:
    push:
        branches:
            - '*'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: '20.x'

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@v1.10.0
              with:
                  mongodb-version: '7.0.2'
                  mongodb-username: 'admin'
                  mongodb-password: 'admin'

            - name: Install dependencies
              run: npm ci

            - name: Run API tests
              run: npm test
              env:
                  MONGODB_URI: mongodb://admin:admin@localhost:27017
                  JWT_SECRET: secret
                  AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=account;AccountKey=key;EndpointSuffix=core.windows.net'

            - name: Run UI tests
              run: npm run test-ui
              env:
                  MONGODB_URI: mongodb://admin:admin@localhost:27017
                  JWT_SECRET: secret
                  AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=account;AccountKey=key;EndpointSuffix=core.windows.net'
